In [3]:
import numpy as np
import pandas as pd
import re

from base import building_blocks

In [257]:
from db import mendeleev

In [260]:
mendeleev

,chemical_symbol,ionization_energy,oxidation_states,screening_constant,neutrons,mass_number,hardness,softness,Zeff_slater,Zeff_clementi,...,electronegativity_allred-rochow,electronegativity_cottrell-sutton,electronegativity_ghosh,electronegativity_gordy,electronegativity_li-xue,electronegativity_martynov-batsanov,electronegativity_mulliken,electronegativity_nagle,electronegativity_pauling,electronegativity_sanderson
0,H,{1: 13.598434005136},"[1, -1]","{(1, 's'): 0.0}",0,1,6.422120,0.077856,1.00,1.0000,...,0.000977,0.176777,0.263800,0.031250,"{('I', ''): -3.540721753312244, ('II', ''): -2...",3.687605,6.799217,0.605388,2.20,2.187771
1,He,"{1: 24.587387936, 2: 54.41776311}",[0],"{(1, 's'): 0.3125}",2,4,22.143694,0.022580,1.70,1.6875,...,0.000803,0.192241,0.442712,0.036957,{},6.285107,12.293694,1.130639,NaN,1.000000
2,Li,"{1: 5.391714761, 2: 75.6400937, 3: 122.4543538}",[1],"{(1, 's'): 0.3094000000000001, (2, 's'): 1.7208}",4,7,2.386833,0.209483,1.30,1.2792,...,0.000073,0.098866,0.105093,0.009774,"{('IV', ''): 1.7160634314550876, ('VI', ''): 1...",2.322007,2.695857,0.182650,0.98,0.048868
3,Be,"{1: 9.322699, 2: 18.211153, 3: 153.896198, 4: ...",[2],"{(1, 's'): 0.3151999999999999, (2, 's'): 2.088}",5,9,5.861350,0.085305,1.95,1.9120,...,0.000187,0.138267,0.144986,0.019118,{},3.710381,4.661350,0.375615,1.57,0.126847
4,B,"{1: 8.298019, 2: 25.15483, 3: 37.93058, 4: 259...",[3],"{(1, 's'): 0.3205, (2, 'p'): 2.5786, (2, 's'):...",6,11,4.009148,0.124715,2.60,2.4214,...,0.000360,0.174895,0.184886,0.030588,{},4.877958,4.149010,0.526974,2.04,0.254627
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,Fl,{},[],{},173,287,NaN,NaN,5.65,NaN,...,0.000276,0.198772,NaN,0.039510,{},NaN,NaN,0.505320,NaN,1.276548
114,Mc,{},[],{},173,288,NaN,NaN,6.30,NaN,...,0.000240,0.197203,NaN,0.038889,{},NaN,NaN,0.412956,NaN,0.885995
115,Lv,{},[],{},175,291,NaN,NaN,6.95,NaN,...,0.000227,0.199284,NaN,0.039714,{},NaN,NaN,NaN,NaN,0.709221
116,Ts,{},[],{},176,293,NaN,NaN,7.60,NaN,...,0.000279,0.214617,NaN,0.046061,{},NaN,NaN,0.451608,NaN,0.853791
117,Og,{},[],{},176,294,NaN,NaN,8.25,NaN,...,0.000335,0.229233,NaN,0.052548,{},NaN,NaN,0.516679,NaN,1.000000

In [267]:
medel=mendeleev[mendeleev.columns[0:9]]
medel

,chemical_symbol,ionization_energy,oxidation_states,screening_constant,neutrons,mass_number,hardness,softness,Zeff_slater
0,H,{1: 13.598434005136},"[1, -1]","{(1, 's'): 0.0}",0,1,6.422120,0.077856,1.00
1,He,"{1: 24.587387936, 2: 54.41776311}",[0],"{(1, 's'): 0.3125}",2,4,22.143694,0.022580,1.70
2,Li,"{1: 5.391714761, 2: 75.6400937, 3: 122.4543538}",[1],"{(1, 's'): 0.3094000000000001, (2, 's'): 1.7208}",4,7,2.386833,0.209483,1.30
3,Be,"{1: 9.322699, 2: 18.211153, 3: 153.896198, 4: ...",[2],"{(1, 's'): 0.3151999999999999, (2, 's'): 2.088}",5,9,5.861350,0.085305,1.95
4,B,"{1: 8.298019, 2: 25.15483, 3: 37.93058, 4: 259...",[3],"{(1, 's'): 0.3205, (2, 'p'): 2.5786, (2, 's'):...",6,11,4.009148,0.124715,2.60
...,...,...,...,...,...,...,...,...,...
113,Fl,{},[],{},173,287,NaN,NaN,5.65
114,Mc,{},[],{},173,288,NaN,NaN,6.30
115,Lv,{},[],{},175,291,NaN,NaN,6.95
116,Ts,{},[],{},176,293,NaN,NaN,7.60
117,Og,{},[],{},176,294,NaN,NaN,8.25

In [272]:
medel=medel.drop(['ionization_energy' , 'oxidation_states','screening_constant'], axis=1)

In [273]:
medel

    chemical_symbol  neutrons  mass_number   hardness  softness  Zeff_slater
0                 H         0            1   6.422120  0.077856         1.00
1                He         2            4  22.143694  0.022580         1.70
2                Li         4            7   2.386833  0.209483         1.30
3                Be         5            9   5.861350  0.085305         1.95
4                 B         6           11   4.009148  0.124715         2.60
..              ...       ...          ...        ...       ...          ...
113              Fl       173          287        NaN       NaN         5.65
114              Mc       173          288        NaN       NaN         6.30
115              Lv       175          291        NaN       NaN         6.95
116              Ts       176          293        NaN       NaN         7.60
117              Og       176          294        NaN       NaN         8.25

[118 rows x 6 columns]

In [308]:
def statistical_feature_values(compound,feature_collection,feature_name,statistical_name='all'):
    '''
    this funtion
    '''
    column_names=[]
    atoms = building_blocks(compound,'element')
    # for idx in range(len(atoms)):
    #     column_names.append('{}_{}_{}'.format(feature_name,idx+1,atoms[idx]))
    mat_fea_vals=[]
    for atom in atoms:
        tmp_val = feature_collection.loc[feature_collection['chemical_symbol'] == atom][feature_name].values
        mat_fea_vals.append(tmp_val[0])
    mat_fea_vals_array = np.array(mat_fea_vals)
    
    min_value=mat_fea_vals_array.min()
    max_value=mat_fea_vals_array.max()
    mean_value=mat_fea_vals_array.mean()
    std_value=mat_fea_vals_array.std()
    sum_value=mat_fea_vals_array.sum()
    diff_value=min_value=max_value-min_value
    tmp_dict={'min':min_value, 'max':max_value, 'mean':mean_value, 'std':std_value, 'diff':diff_value, 'sum':sum_value}


    if (statistical_name=='all'):
        for i in tmp_dict.keys():
            column_names.append(feature_name+'_{}'.format(i))
            # print(column_names)
        return column_names, list(tmp_dict.values())
    elif isinstance(statistical_name, list):
        tmp_lst=[]
        for i in statistical_name:
            # print(i)
            tmp_lst.append(tmp_dict[i])
        return tmp_lst
    elif statistical_name != 'all' and isinstance(statistical_name, str):
        tmp_lst=[]
        tmp_lst.append(tmp_dict[statistical_name])
        return tmp_lst

In [309]:
compound='Al2O3'

In [310]:
lst=['min' , 'max']

In [311]:
statistic_feature_values(compound ,mendeleev, 'atomic_number')

(['atomic_number_min',
  'atomic_number_max',
  'atomic_number_mean',
  'atomic_number_std',
  'atomic_number_diff',
  'atomic_number_sum'],
 [5, 13, 10.5, 2.5, 5, 21])

In [385]:
def statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name,statistical_name='all'):

    dataframe_name["Feature"]=dataframe_name[column_name].apply(statistical_feature_values,feature_collection=feature_collection,feature_name=feature_name,statistical_name='all')
    # dataframe_name["Elements"]=dataframe_name[column_name].apply(building_blocks,option='element')
    # dataframe_name["Number_of_Elements"]=dataframe_name["Elements"].apply(len)
    # unique_elements = dataframe_name["Number_of_Elements"].unique()
    # max_n_elements = dataframe_name["Number_of_Elements"].max()
    # column_names=[]
    # for i in range(max_n_elements):
    #     column_names.append('{}_{}'.format(feature_name,i+1))
    # pd.concat([dataframe_name,pd.DataFrame(columns=column_names)])
    # for i in range(len(dataframe_name)):
    #     for j in range(dataframe_name.Number_of_Elements.iloc[i]):
    #         dataframe_name.loc[dataframe_name.index[i],column_names[j]]=(dataframe_name['Feature'])[i][1][j]
    
    # return dataframe_name.drop(["Feature","Elements","Number_of_Elements"],axis=1)
    return dataframe_name.drop(["Feature"],axis=1)

In [386]:
lst_f=['atomic_number', 'atomic_weight']

In [389]:
statistical_feature_values_df(primary_data ,medel, 'formula')

TypeError: expected string or bytes-like object

In [362]:
def statistical_features(compound,feature_collection,feature='all',statistical_name='all'):

    if (feature=='all'):
        tmp_all_list=[]
        column_list=feature_collection.keys().drop('chemical_symbol')
    for i in range(len(column_list)):
            tmp_all_list.append(statistical_feature_values(compound,feature_collection,feature_name=(column_list)[i],statistical_name='all'))
        return tmp_all_list
    elif isinstance(feature, list):
        tmp_list=[]
        for i in range(len(feature)):
            tmp_list.append(statistical_feature_values(compound,feature_collection,feature_name=feature[i],statistical_name='all'))
        return tmp_list
    elif feature != 'all' and isinstance(feature, str):
        return statistical_feature_values(compound,feature_collection,feature_name=feature,statistical_name='all')
    #     return type(arg)
    # if isinstance(arg, pymatgen.core.composition.Composition):
    #     return type(arg)
    # else:
        # return "Not a dataframe"

In [363]:
get_features(compound ,medel)

[(['neutrons_min',
   'neutrons_max',
   'neutrons_mean',
   'neutrons_std',
   'neutrons_diff',
   'neutrons_sum'],
  [6, 14, 11.0, 3.0, 6, 22]),
 (['mass_number_min',
   'mass_number_max',
   'mass_number_mean',
   'mass_number_std',
   'mass_number_diff',
   'mass_number_sum'],
  [11, 27, 21.5, 5.5, 11, 43]),
 (['hardness_min',
   'hardness_max',
   'hardness_mean',
   'hardness_std',
   'hardness_diff',
   'hardness_sum'],
  [3.3020010500000003,
   6.0784702500000005,
   4.427469725,
   1.6510005250000002,
   3.3020010500000003,
   8.85493945]),
 (['softness_min',
   'softness_max',
   'softness_mean',
   'softness_std',
   'softness_diff',
   'softness_sum'],
  [0.09782729740556291,
   0.1800848358051297,
   0.13117118710234826,
   0.048913648702781455,
   0.09782729740556291,
   0.2623423742046965]),
 (['Zeff_slater_min',
   'Zeff_slater_max',
   'Zeff_slater_mean',
   'Zeff_slater_std',
   'Zeff_slater_diff',
   'Zeff_slater_sum'],
  [1.0499999999999998,
   4.55,
   4.025,
   0.5249999999999999,
   1.0499999999999998,
   8.05])]

In [364]:
def statistical_features_df(dataframe_name,column_name,feature_collection,feature='all',statistical_name='all'):
    if (feature=='all'):
        # for i in range(len(feature_collection.keys())):
        tmp_all_list=[]
        column_list=feature_collection.keys().drop('chemical_symbol')
        for i in range(len(column_list)):
            tmp_all_df=statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=(column_list)[i])
        return tmp_all_df
    elif isinstance(feature, list):
        tmp_list=[]
        for i in range(len(feature)):
            tmp_list_df=statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=feature[i])
        return tmp_list_df
    elif feature != 'all' and isinstance(feature, str):
        return statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=feature,statistical_name='all')

In [365]:
def fetch_features(compounds, collection, features='all', column_name=None, statistical_name='all'):
    if isinstance(compounds, str):
        # return get_features(compounds,collection,features)
        if features !='all' and isinstance(features, str):
            values= [statistical_features(compounds,collection,features ,statistical_name='all')[1]]
            names = statistical_features(compounds,collection,features ,statistical_name='all')[0]
            return pd.DataFrame(values,columns=names,index=[compounds])
        else :
            n_features=len(statistical_features(compounds,collection,features))
            n_elements=len(statistical_features(compounds,collection,features)[0][0])
            tmp_array=np.array(statistical_features(compounds,collection,features))
            names=list(tmp_array[:,0].reshape(1,n_features*n_elements)[0])
            values=tmp_array[:,1].reshape(1,n_features*n_elements)
            return pd.DataFrame(values,columns=names,index=[compounds])
    if isinstance(compounds, list):
        tmp_df=pd.DataFrame(compounds,columns=["formula"])
        # return tmp_df
        return statistical_features_df(tmp_df,"formula",collection,features, statistical_name='all')
    if isinstance(compounds, pd.DataFrame):
        tmp_dataframe_name=compounds.copy(deep=True)
        if (column_name==None):
            raise ValueError("The input is `pd.DataFrame` and `column_name` argument is not given. Please inter materials column name.")
        else :
            return statistical_features_df(tmp_dataframe_name,column_name,collection,features, statistical_name='all')

In [366]:
fetch_features(compound , mendeleev,  'atomic_number', 'all')

,atomic_number_min,atomic_number_max,atomic_number_mean,atomic_number_std,atomic_number_diff,atomic_number_sum
Al2O3,5,13,10.5,2.5,5,21

In [367]:
fetch_features(compound ,medel)

,neutrons_min,neutrons_max,neutrons_mean,neutrons_std,neutrons_diff,neutrons_sum,mass_number_min,mass_number_max,mass_number_mean,mass_number_std,...,softness_mean,softness_std,softness_diff,softness_sum,Zeff_slater_min,Zeff_slater_max,Zeff_slater_mean,Zeff_slater_std,Zeff_slater_diff,Zeff_slater_sum
Al2O3,6,14,11.0,3.0,6,22,11,27,21.5,5.5,...,0.13117118710234826,0.048913648702781455,0.09782729740556291,0.2623423742046965,1.0499999999999998,4.55,4.025,0.5249999999999999,1.0499999999999998,8.05

In [368]:
primary_data=pd.read_csv("/home/saeid/ML/papers/Benchmark/JCTC - Large Scale Benchmark of Exchange Correlation Functionals for the Determination of Electronic Band Gaps of Solids/python/downloaded_list.csv", index_col=0)

In [369]:
primary_data

              formula  space group  bandgap
mp-28222    Rb3Sb2Br9          164   1.9796
mp-17756    RbAg2SbS4          154   0.6178
mp-30373         RbAu          221   0.3699
mp-22867         RbBr          225   4.1920
mp-23295         RbCl          225   4.8388
...               ...          ...      ...
mp-10519      Cu2SnS3            9   0.0183
mp-11658     Cu2SnSe3            9   0.0000
mp-1861         Cu2Te          191   0.0000
mp-10824   ZnCu2GeSe4          121   0.0000
mp-977414   ZnCu2SiS4           31   1.2823

[471 rows x 3 columns]

In [370]:
fetch_features(primary_data ,medel, column_name='formula')

              formula  space group  bandgap
mp-28222    Rb3Sb2Br9          164   1.9796
mp-17756    RbAg2SbS4          154   0.6178
mp-30373         RbAu          221   0.3699
mp-22867         RbBr          225   4.1920
mp-23295         RbCl          225   4.8388
...               ...          ...      ...
mp-10519      Cu2SnS3            9   0.0183
mp-11658     Cu2SnSe3            9   0.0000
mp-1861         Cu2Te          191   0.0000
mp-10824   ZnCu2GeSe4          121   0.0000
mp-977414   ZnCu2SiS4           31   1.2823

[471 rows x 3 columns]