In [1]:
import numpy as np
import pandas as pd
import re

from base import building_blocks
from db import mendeleev

In [2]:
# tmp_dict={'min':'min_value', 'max':'max_value', 'sum':'sum_value',
#                 'diff':'diff_value', 'mean':'mean_value', 'std':'std_value'}

In [3]:

def statistical_feature_values(compound,feature_collection,feature_name,statistical_functions='all'):

    column_names=[]
    atoms = building_blocks(compound,'element')
    # for idx in range(len(atoms)):
    #     column_names.append('{}_{}_{}'.format(feature_name,idx+1,atoms[idx]))
    stats_fea_vals=[]
    for atom in atoms:
        tmp_val = feature_collection.loc[feature_collection['chemical_symbol'] == atom][feature_name].values
        stats_fea_vals.append(tmp_val[0])

    stats_fea_vals_array = np.array(stats_fea_vals)

    min_value    = stats_fea_vals_array.min()
    max_value    = stats_fea_vals_array.max()
    sum_value    = stats_fea_vals_array.sum()
    diff_value   = min_value=max_value-min_value
    mean_value   = stats_fea_vals_array.mean()
    std_value    = stats_fea_vals_array.std()
    # median_value = stat_fea_vals_array.median()

    tmp_dict={'min':min_value, 'max':max_value, 'sum':sum_value, 'diff':diff_value, 'mean':mean_value, 'std':std_value}

    if (statistical_functions=='all'):
        for i in tmp_dict.keys():
            column_names.append(feature_name+'_{}'.format(i))
            # print(column_names)
        return column_names, list(tmp_dict.values())
    elif isinstance(statistical_functions, list):
        tmp_lst=[]
        for i in statistical_functions:
            # print(i)
            column_names.append(feature_name+'_{}'.format(i))
            # print(column_names)
            tmp_lst.append(tmp_dict[i])
        return column_names,tmp_lst
    elif statistical_functions != 'all' and isinstance(statistical_functions, str):
        if statistical_functions not in tmp_dict.keys():
            raise ValueError("The `statistical_functions` parameter should be one of the `min`, `max`, `sum`, `diff`, `mean`, `median` or `all` valuse")
        else:
            tmp_lst=[]
            column_names.append(feature_name+'_{}'.format(statistical_functions))
            tmp_lst.append(tmp_dict[statistical_functions])
            return column_names,tmp_lst

    # return column_names, mat_fea_vals

In [4]:
statistical_feature_values('Al2O3' ,mendeleev, 'atomic_number',statistical_functions='all')

(['atomic_number_min',
  'atomic_number_max',
  'atomic_number_sum',
  'atomic_number_diff',
  'atomic_number_mean',
  'atomic_number_std'],
 [5, 13, 21, 5, 10.5, 2.5])

In [5]:
statistical_feature_values('Al2O3' ,mendeleev, 'atomic_number',statistical_functions=['max','min'])

(['atomic_number_max', 'atomic_number_min'], [13, 5])

In [6]:
statistical_feature_values('Al2O3' ,mendeleev, 'atomic_number',statistical_functions='max')

(['atomic_number_max'], [13])

In [7]:
# def statistical_features(compound,feature_collection,feature='all',statistical_functions='all'):

#     if (feature=='all'):
#         tmp_all_list=[]
#         feature_list=feature_collection.keys().drop('chemical_symbol')
#         for i in range(len(feature_list)):
#             # print(i)
#             tmp_all_list.append(statistical_feature_values(compound,feature_collection,feature_name=feature_list[i],statistical_functions=statistical_functions))
#         return tmp_all_list
#     elif isinstance(feature, list):
#         tmp_list=[]
#         for i in range(len(feature)):
#             tmp_list.append(statistical_feature_values(compound,feature_collection,feature_name=feature[i],statistical_functions=statistical_functions))
#         return tmp_list
#     elif feature != 'all' and isinstance(feature, str):
#         return statistical_feature_values(compound,feature_collection,feature_name=feature,statistical_functions=statistical_functions)
#     #     return type(arg)
#     # if isinstance(arg, pymatgen.core.composition.Composition):
#     #     return type(arg)
#     # else:
#         # return "Not a dataframe"

In [8]:
# def statistical_features(compound,feature_collection,feature='all',statistical_functions='all'):

#     if (feature=='all'):
#         tmp_all_list=[]
#         feature_list=feature_collection.keys()
#         for i in range(len(feature_list)):
#             # print(i)
#             if is_numeric_dtype(feature_collection[list[i]])==True:
#                 tmp_all_list.append(statistical_feature_values(compound,feature_collection,feature_name=feature_list[i],statistical_functions=statistical_functions))
#         return tmp_all_list
#     elif isinstance(feature, list):
#         tmp_list=[]
#         for i in range(len(feature)):
#             tmp_list.append(statistical_feature_values(compound,feature_collection,feature_name=feature[i],statistical_functions=statistical_functions))
#         return tmp_list
#     elif feature != 'all' and isinstance(feature, str):
#         return statistical_feature_values(compound,feature_collection,feature_name=feature,statistical_functions=statistical_functions)
#     #     return type(arg)
#     # if isinstance(arg, pymatgen.core.composition.Composition):
#     #     return type(arg)
#     # else:
#         # return "Not a dataframe"

In [51]:
def statistical_features(compound,feature_collection,feature='all',statistical_functions='all'):

    if (feature=='all'):
        tmp_all_list=[]
        fea_collection_keys_list=feature_collection.keys()
        for i in range(len( fea_collection_keys_list )):
            # print(i)
            if is_numeric_dtype(feature_collection[fea_collection_keys_list[i]])==True:
                tmp_all_list.append(statistical_feature_values(compound,feature_collection,feature_name=fea_collection_keys_list[i],statistical_functions=statistical_functions))
        return tmp_all_list
    elif isinstance(feature, list):
        tmp_list=[]
        for i in range(len(feature)):
            tmp_list.append(statistical_feature_values(compound,feature_collection,feature_name=feature[i],statistical_functions=statistical_functions))
        return tmp_list
    elif feature != 'all' and isinstance(feature, str):
        return statistical_feature_values(compound,feature_collection,feature_name=feature,statistical_functions=statistical_functions)
    #     return type(arg)
    # if isinstance(arg, pymatgen.core.composition.Composition):
    #     return type(arg)
    # else:
        # return "Not a dataframe"

In [52]:
mendel=mendeleev[mendeleev.columns[0:9]]
mendel=mendel.drop(['ionization_energy' , 'oxidation_states','screening_constant'], axis=1)
mendel

    chemical_symbol  neutrons  mass_number   hardness  softness  Zeff_slater
0                 H         0            1   6.422120  0.077856         1.00
1                He         2            4  22.143694  0.022580         1.70
2                Li         4            7   2.386833  0.209483         1.30
3                Be         5            9   5.861350  0.085305         1.95
4                 B         6           11   4.009148  0.124715         2.60
..              ...       ...          ...        ...       ...          ...
113              Fl       173          287        NaN       NaN         5.65
114              Mc       173          288        NaN       NaN         6.30
115              Lv       175          291        NaN       NaN         6.95
116              Ts       176          293        NaN       NaN         7.60
117              Og       176          294        NaN       NaN         8.25

[118 rows x 6 columns]

In [53]:
# statistical_features("Al2Fe3O",mendel,feature='all')

In [54]:
statistical_features("Rb3Sb2Br9",mendeleev,'atomic_number')

(['atomic_number_min',
  'atomic_number_max',
  'atomic_number_sum',
  'atomic_number_diff',
  'atomic_number_mean',
  'atomic_number_std'],
 [16, 51, 123, 16, 41.0, 7.118052168020874])

In [55]:
statistical_features("Rb3Sb2Br9",mendeleev,['atomic_number','pettifor_number'])

[(['atomic_number_min',
   'atomic_number_max',
   'atomic_number_sum',
   'atomic_number_diff',
   'atomic_number_mean',
   'atomic_number_std'],
  [16, 51, 123, 16, 41.0, 7.118052168020874]),
 (['pettifor_number_min',
   'pettifor_number_max',
   'pettifor_number_sum',
   'pettifor_number_diff',
   'pettifor_number_mean',
   'pettifor_number_std'],
  [89.0, 98.0, 195.0, 89.0, 65.0, 39.80787191833629])]

In [56]:
primary_data=pd.read_csv("/home/saeid/ML/papers/Benchmark/JCTC - Large Scale Benchmark of Exchange Correlation Functionals for the Determination of Electronic Band Gaps of Solids/python/downloaded_list.csv", index_col=0)

In [57]:
primary_data

              formula  space group  bandgap
mp-28222    Rb3Sb2Br9          164   1.9796
mp-17756    RbAg2SbS4          154   0.6178
mp-30373         RbAu          221   0.3699
mp-22867         RbBr          225   4.1920
mp-23295         RbCl          225   4.8388
...               ...          ...      ...
mp-10519      Cu2SnS3            9   0.0183
mp-11658     Cu2SnSe3            9   0.0000
mp-1861         Cu2Te          191   0.0000
mp-10824   ZnCu2GeSe4          121   0.0000
mp-977414   ZnCu2SiS4           31   1.2823

[471 rows x 3 columns]

In [58]:
# def statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name,statistical_functions):
    
#     dataframe_name[['stat_name','stat_value']]=pd.DataFrame(dataframe_name[column_name].apply(statistical_feature_values,feature_collection=feature_collection
#                                                                                               ,feature_name=feature_name,statistical_functions=statistical_functions).tolist())
    
#     column_names=dataframe_name['stat_name'].tolist()[0]
#     new_data=pd.DataFrame(dataframe_name['stat_value'].tolist(),columns=column_names,index=dataframe_name[column_name])

    
#     return new_data

In [59]:
def statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name,statistical_functions='all'):

    dataframe_name["Feature"]=dataframe_name[column_name].apply(statistical_feature_values,feature_collection=feature_collection,feature_name=feature_name,statistical_functions=statistical_functions)
    # return dataframe_name
    # dataframe_name["Elements"]=dataframe_name[column_name].apply(building_blocks,option='element')
    # dataframe_name["Number_of_Elements"]=dataframe_name["Elements"].apply(len)
    # # unique_elements = dataframe_name["Number_of_Elements"].unique()
    # max_n_elements = dataframe_name["Number_of_Elements"].max()
    # column_names=[]
    # for i in (dataframe_name["Feature"][0][0]):
    #     # print(i)
    #     column_names.append('{}'.format(i))
    # pd.concat([dataframe_name,pd.DataFrame(columns=column_names)])
    # for i in range(len(dataframe_name)):
    #     for j in range(dataframe_name.Number_of_Elements.iloc[i]):
    #         dataframe_name.loc[dataframe_name.index[i],column_names[j]]=(dataframe_name['Feature'])[i][1][j]
    tmp_dataframe=pd.DataFrame(dataframe_name['Feature'].tolist(), index=dataframe_name.index, columns=['lst_col_names','lst_values'])
    tmp_col_names_lst=tmp_dataframe.lst_col_names[0]
    
    tmp_dataframe[tmp_col_names_lst] = pd.DataFrame(tmp_dataframe.lst_values.tolist(), index= tmp_dataframe.index)


    # return dataframe_name.drop(["Feature","Elements","Number_of_Elements"],axis=1)
    # return dataframe_name.drop(["Feature"],axis=1)
    # return pd.concat([dataframe_name.drop('Feature',axis=1),tmp_dataframe.drop(['lst_col_names','lst_values'],axis=1)],axis=1)
    dataframe_name=pd.concat([dataframe_name.drop('Feature',axis=1),tmp_dataframe.drop(['lst_col_names','lst_values'],axis=1)],axis=1)
    return dataframe_name

In [60]:
# primary_data['Feature'] = primary_data['formula'].apply(statistical_feature_values,feature_collection=mendeleev,feature_name='atomic_number',statistical_functions='all')
# primary_data

In [61]:
# column_names=[]
# for i in (primary_data["Feature"][0][0]):
#     # print(i)
#     column_names.append('{}'.format(i))

In [62]:
# tmp_dataframe=pd.DataFrame(primary_data['Feature'].tolist(), index=primary_data.index, columns=['tmp_col_names','lst_values'])
# tmp_dataframe

In [63]:
# tmp_col_names_lst=tmp_dataframe.tmp_col_names[0]
# tmp_col_names_lst

In [64]:
# tmp_dataframe[tmp_col_names_lst] = pd.DataFrame(tmp_dataframe.lst_values.tolist(), index= a.index)
# tmp_dataframe

In [65]:
# tmpp=pd.concat([primary_data.drop('Feature',axis=1),tmp_dataframe.drop(['tmp_col_names','lst_values'],axis=1)],axis=1)
# tmpp

In [66]:
# def statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name,statistical_functions='all'):

#     dataframe_name["Feature"]=dataframe_name[column_name].apply(statistical_feature_values,feature_collection=feature_collection,feature_name=feature_name,statistical_functions='all')
#     # return dataframe_name
#     # dataframe_name["Elements"]=dataframe_name[column_name].apply(building_blocks,option='element')
#     # dataframe_name["Number_of_Elements"]=dataframe_name["Elements"].apply(len)
#     # # unique_elements = dataframe_name["Number_of_Elements"].unique()
#     # max_n_elements = dataframe_name["Number_of_Elements"].max()
#     column_names=[]
#     for i in (dataframe_name["Feature"][0][0]):
#         # print(i)
#         column_names.append('{}'.format(i))
#     # pd.concat([dataframe_name,pd.DataFrame(columns=column_names)])
#     # for i in range(len(dataframe_name)):
#     #     for j in range(dataframe_name.Number_of_Elements.iloc[i]):
#     #         dataframe_name.loc[dataframe_name.index[i],column_names[j]]=(dataframe_name['Feature'])[i][1][j]
#     tmp_dataframe=pd.DataFrame(dataframe_name['Feature'].tolist(), index=dataframe_name.index, columns=['tmp_col_names','lst_values'])
#     tmp_col_names_lst=tmp_dataframe.tmp_col_names[0]
    
#     tmp_dataframe[tmp_col_names_lst] = pd.DataFrame(tmp_dataframe.lst_values.tolist(), index= tmp_dataframe.index)
#     tmpp=pd.concat([dataframe_name.drop('Feature',axis=1),tmp_dataframe.drop(['tmp_col_names','lst_values'],axis=1)],axis=1)
#     dataframe_name=tmpp.copy()


#     # return dataframe_name.drop(["Feature","Elements","Number_of_Elements"],axis=1)
#     # return dataframe_name.drop(["Feature"],axis=1)
#     return dataframe_name

In [67]:
# statistical_feature_values_df(primary_data,'formula',mendeleev,'atomic_weight')
statistical_feature_values_df(primary_data,column_name='formula',feature_collection=mendeleev, feature_name='atomic_number',statistical_functions='all')

,formula,space group,bandgap,atomic_number_min,atomic_number_max,atomic_number_sum,atomic_number_diff,atomic_number_mean,atomic_number_std
mp-28222,Rb3Sb2Br9,164,1.9796,16,51,123,16,41.000000,7.118052
mp-17756,RbAg2SbS4,154,0.6178,35,51,151,35,37.750000,13.553136
mp-30373,RbAu,221,0.3699,42,79,116,42,58.000000,21.000000
mp-22867,RbBr,225,4.1920,2,37,72,2,36.000000,1.000000
mp-23295,RbCl,225,4.8388,20,37,54,20,27.000000,10.000000
...,...,...,...,...,...,...,...,...,...
mp-10519,Cu2SnS3,9,0.0183,34,50,95,34,31.666667,14.007934
mp-11658,Cu2SnSe3,9,0.0000,21,50,113,21,37.666667,8.956686
mp-1861,Cu2Te,191,0.0000,23,52,81,23,40.500000,11.500000
mp-10824,ZnCu2GeSe4,121,0.0000,5,34,125,5,31.250000,1.920286
mp-977414,ZnCu2SiS4,31,1.2823,16,30,89,16,22.250000,7.292976

In [68]:
# dffff=statistical_feature_values_df(primary_data,'formula',mendeleev,'atomic_weight')
# dffff.Feature[0]

In [69]:
# a=pd.DataFrame(dffff['Feature'].tolist(), index=dffff.index, columns=['namess','valuess'])

In [70]:
# a

In [71]:
# a.namess[0]

In [72]:
# a[['valuess']]

In [73]:
# a[['atomic_weight_min',
#   'atomic_weight_max',
#   'atomic_weight_sum',
#   'atomic_weight_diff',
#   'atomic_weight_mean',
#   'atomic_weight_std']] = pd.DataFrame(a.valuess.tolist(), index= a.index)

In [74]:
# a

In [75]:
# def statistical_features_df(dataframe_name,column_name,feature_collection,feature='all',statistical_functions='all'):
#     if (feature=='all'):
#         # for i in range(len(feature_collection.keys())):
#         tmp_all_list=[]
#         column_list=feature_collection.keys().drop('chemical_symbol')
#         # print(column_list)
#         tmp_all_df=dataframe_name.copy()
#         for i in range(len(column_list)):
#             print(column_list[i])
#             tmp_all_df=statistical_feature_values_df(tmp_all_df,column_name,feature_collection,feature_name=column_list[i],statistical_functions=statistical_functions).copy()
#             print(i)
#             # tmp_all_list.append(tmp_all_df)
#             # tmp_all_list=pd.concat(tmp_all_list, ignore_index=True)
#         print('ok')
#         # return tmp_all_df
#         return statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=column_list[i],statistical_functions=statistical_functions)
#     elif isinstance(feature, list):
#         tmp_list=[]
#         for i in range(len(feature)):
#             tmp_list_df=statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=feature[i],statistical_functions=statistical_functions)
#         return tmp_list_df
#     elif feature != 'all' and isinstance(feature, str):
#         return statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=feature,statistical_functions=statistical_functions)

In [76]:
# def statistical_features_df(dataframe_name,column_name,feature_collection,feature='all',statistical_functions='all'):
#     if (feature=='all'):
#         fea_collection_keys_list=feature_collection.keys().drop('chemical_symbol')
#         for i in range(len( fea_collection_keys_list )):
#             # print(fea_collection_keys_list[i])
#             dataframe_name=statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=(fea_collection_keys_list[i]),statistical_functions=statistical_functions)
#             # tttt=pd.concat([dataframe_name,tmp_all_df],axis=1)
#             # dataframe_name=tttt.copy()
#             # display(tmp_all_df)
#         # return tmp_all_df
#         return dataframe_name
#     elif isinstance(feature, list):
#         tmp_list=[]
#         for i in range(len(feature)):
#             dataframe_name=statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=feature[i],statistical_functions=statistical_functions)
#         return dataframe_name
#     elif feature != 'all' and isinstance(feature, str):
#         return statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=feature,statistical_functions=statistical_functions)
#     #     return type(arg)
#     # if isinstance(arg, pymatgen.core.composition.Composition):
#     #     return type(arg)
#     # else:
#         # return "Not a dataframe"

In [114]:
for i in mendeleev.keys():
    if (is_numeric_dtype(mendeleev[i])==False):
        print(i)

chemical_symbol
ionization_energy
oxidation_states
screening_constant
electron_configuration
electrons_per_shell
max_l
last_subshell
spin_occupations
oxides
block_periodic_table
description
electronic_configuration
lattice_structure
chemical_name
electronegativity_li-xue

In [115]:
mendeleev

,chemical_symbol,ionization_energy,oxidation_states,screening_constant,neutrons,mass_number,hardness,softness,Zeff_slater,Zeff_clementi,...,electronegativity_allred-rochow,electronegativity_cottrell-sutton,electronegativity_ghosh,electronegativity_gordy,electronegativity_li-xue,electronegativity_martynov-batsanov,electronegativity_mulliken,electronegativity_nagle,electronegativity_pauling,electronegativity_sanderson
0,H,{1: 13.598434005136},"[1, -1]","{(1, 's'): 0.0}",0,1,6.422120,0.077856,1.00,1.0000,...,0.000977,0.176777,0.263800,0.031250,"{('I', ''): -3.540721753312244, ('II', ''): -2...",3.687605,6.799217,0.605388,2.20,2.187771
1,He,"{1: 24.587387936, 2: 54.41776311}",[0],"{(1, 's'): 0.3125}",2,4,22.143694,0.022580,1.70,1.6875,...,0.000803,0.192241,0.442712,0.036957,{},6.285107,12.293694,1.130639,NaN,1.000000
2,Li,"{1: 5.391714761, 2: 75.6400937, 3: 122.4543538}",[1],"{(1, 's'): 0.3094000000000001, (2, 's'): 1.7208}",4,7,2.386833,0.209483,1.30,1.2792,...,0.000073,0.098866,0.105093,0.009774,"{('IV', ''): 1.7160634314550876, ('VI', ''): 1...",2.322007,2.695857,0.182650,0.98,0.048868
3,Be,"{1: 9.322699, 2: 18.211153, 3: 153.896198, 4: ...",[2],"{(1, 's'): 0.3151999999999999, (2, 's'): 2.088}",5,9,5.861350,0.085305,1.95,1.9120,...,0.000187,0.138267,0.144986,0.019118,{},3.710381,4.661350,0.375615,1.57,0.126847
4,B,"{1: 8.298019, 2: 25.15483, 3: 37.93058, 4: 259...",[3],"{(1, 's'): 0.3205, (2, 'p'): 2.5786, (2, 's'):...",6,11,4.009148,0.124715,2.60,2.4214,...,0.000360,0.174895,0.184886,0.030588,{},4.877958,4.149010,0.526974,2.04,0.254627
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,Fl,{},[],{},173,287,NaN,NaN,5.65,NaN,...,0.000276,0.198772,NaN,0.039510,{},NaN,NaN,0.505320,NaN,1.276548
114,Mc,{},[],{},173,288,NaN,NaN,6.30,NaN,...,0.000240,0.197203,NaN,0.038889,{},NaN,NaN,0.412956,NaN,0.885995
115,Lv,{},[],{},175,291,NaN,NaN,6.95,NaN,...,0.000227,0.199284,NaN,0.039714,{},NaN,NaN,NaN,NaN,0.709221
116,Ts,{},[],{},176,293,NaN,NaN,7.60,NaN,...,0.000279,0.214617,NaN,0.046061,{},NaN,NaN,0.451608,NaN,0.853791
117,Og,{},[],{},176,294,NaN,NaN,8.25,NaN,...,0.000335,0.229233,NaN,0.052548,{},NaN,NaN,0.516679,NaN,1.000000

In [77]:
from pandas.api.types import is_numeric_dtype

In [78]:
is_numeric_dtype(mendel['neutrons'])

True

In [79]:
def statistical_features_df(dataframe_name,column_name,feature_collection,feature='all',statistical_functions='all'):
    if (feature=='all'):
        fea_collection_keys_list=feature_collection.keys()
        for i in range(len( fea_collection_keys_list )):
            # print(fea_collection_keys_list[i])
            if is_numeric_dtype(feature_collection[fea_collection_keys_list[i]])==True:
                # print(fea_collection_keys_list[i], 'is numeric')
                dataframe_name=statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=(fea_collection_keys_list[i]),statistical_functions=statistical_functions)
            # tttt=pd.concat([dataframe_name,tmp_all_df],axis=1)
            # dataframe_name=tttt.copy()
            # display(tmp_all_df)
        # return tmp_all_df
        return dataframe_name
    elif isinstance(feature, list):
        tmp_list=[]
        for i in range(len(feature)):
            dataframe_name=statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=feature[i],statistical_functions=statistical_functions)
        return dataframe_name
    elif feature != 'all' and isinstance(feature, str):
        return statistical_feature_values_df(dataframe_name,column_name,feature_collection,feature_name=feature,statistical_functions=statistical_functions)
    #     return type(arg)
    # if isinstance(arg, pymatgen.core.composition.Composition):
    #     return type(arg)
    # else:
        # return "Not a dataframe"

In [80]:
statistical_features_df(primary_data,column_name='formula',feature_collection=mendeleev,feature='all',statistical_functions='min')

,formula,space group,bandgap,neutrons_min,mass_number_min,hardness_min,softness_min,Zeff_slater_min,Zeff_clementi_min,electrophilicity_min,...,electronegativity_allen_min,electronegativity_allred-rochow_min,electronegativity_cottrell-sutton_min,electronegativity_ghosh_min,electronegativity_gordy_min,electronegativity_martynov-batsanov_min,electronegativity_mulliken_min,electronegativity_nagle_min,electronegativity_pauling_min,electronegativity_sanderson_min
mp-28222,Rb3Sb2Br9,164,1.9796,26,42,2.379507,0.152574,5.40,5.0100,2.671161,...,11.703,0.000535,0.155846,0.136572,0.056190,5.166110,3.818341,0.547130,2.14,0.872612
mp-17756,RbAg2SbS4,154,0.6178,54,89,2.295849,0.150183,4.10,5.0100,1.598008,...,11.133,0.000464,0.127674,0.131274,0.042436,4.743727,3.091441,0.530033,1.76,0.767382
mp-30373,RbAu,221,0.3699,70,112,1.612857,0.126341,1.50,5.9535,1.667856,...,7.153,0.000191,0.070386,0.156684,0.019363,1.792117,2.524212,0.527309,1.58,1.250287
mp-22867,RbBr,225,4.1920,4,6,2.379507,0.152574,5.40,4.0435,2.671161,...,11.703,0.000535,0.155846,0.136572,0.056190,5.166110,3.818341,0.547130,2.14,0.872612
mp-23295,RbCl,225,4.8388,30,50,2.831848,0.164018,3.90,1.1316,2.936971,...,12.793,0.000572,0.145873,0.159117,0.051140,5.596715,4.395251,0.636444,2.34,0.635964
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
mp-10519,Cu2SnS3,9,0.0183,54,88,1.025528,0.039735,1.95,3.6201,0.900115,...,4.520,0.000225,0.048270,0.084788,0.019877,3.044618,1.508047,0.253666,0.68,0.277829
mp-11658,Cu2SnSe3,9,0.0000,36,57,0.749936,0.031129,3.25,3.2596,0.806611,...,3.550,0.000228,0.063016,0.072861,0.026878,2.785480,1.204238,0.195864,0.65,0.203632
mp-1861,Cu2Te,191,0.0000,44,67,0.273702,0.011980,3.25,4.9661,0.594808,...,1.800,0.000081,0.044302,0.054528,0.018067,2.334549,0.641640,0.077970,0.20,0.055304
mp-10824,ZnCu2GeSe4,121,0.0000,12,17,NaN,NaN,3.25,2.4448,NaN,...,4.945,0.000222,0.063016,0.072861,0.026878,2.829839,NaN,0.212862,0.90,0.165765
mp-977414,ZnCu2SiS4,31,1.2823,20,36,NaN,NaN,1.75,1.6800,NaN,...,5.915,0.000219,0.048270,0.084788,0.019877,3.088976,NaN,0.201923,0.93,0.570738

In [81]:
# mendeleev

In [82]:
statistical_features_df(primary_data,column_name='formula',feature_collection=mendel,feature='all',statistical_functions='all')

,formula,space group,bandgap,neutrons_min,neutrons_max,neutrons_sum,neutrons_diff,neutrons_mean,neutrons_std,mass_number_min,...,softness_sum,softness_diff,softness_mean,softness_std,Zeff_slater_min,Zeff_slater_max,Zeff_slater_sum,Zeff_slater_diff,Zeff_slater_mean,Zeff_slater_std
mp-28222,Rb3Sb2Br9,164,1.9796,26,70,162,26,54.0,11.430952,42,...,0.521487,0.152574,0.173829,0.068883,5.40,7.60,16.10,5.40,5.366667,2.301207
mp-17756,RbAg2SbS4,154,0.6178,54,70,194,54,48.5,20.316250,89,...,0.683260,0.150183,0.170815,0.059472,4.10,6.30,17.65,4.10,4.412500,1.584446
mp-30373,RbAu,221,0.3699,70,118,166,70,83.0,35.000000,112,...,0.415487,0.126341,0.207743,0.063171,1.50,3.70,5.90,1.50,2.950000,0.750000
mp-22867,RbBr,225,4.1920,4,48,92,4,46.0,2.000000,6,...,0.389254,0.152574,0.194627,0.076287,5.40,7.60,9.80,5.40,4.900000,2.700000
mp-23295,RbCl,225,4.8388,30,48,66,30,33.0,15.000000,50,...,0.377810,0.164018,0.188905,0.082009,3.90,6.10,8.30,3.90,4.150000,1.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
mp-10519,Cu2SnS3,9,0.0183,54,70,120,54,40.0,22.449944,88,...,0.435247,0.039735,0.145082,0.017417,1.95,5.65,14.80,1.95,4.933333,0.875912
mp-11658,Cu2SnSe3,9,0.0000,36,70,150,36,50.0,14.966630,57,...,0.443854,0.031129,0.147951,0.013420,3.25,6.95,16.30,3.25,5.433333,1.335623
mp-1861,Cu2Te,191,0.0000,44,78,112,44,56.0,22.000000,67,...,0.296120,0.011980,0.148060,0.005990,3.25,6.95,10.65,3.25,5.325000,1.625000
mp-10824,ZnCu2GeSe4,121,0.0000,12,46,156,12,39.0,5.196152,17,...,NaN,NaN,NaN,NaN,3.25,6.95,20.65,3.25,5.162500,1.248186
mp-977414,ZnCu2SiS4,31,1.2823,20,34,98,20,24.5,9.526279,36,...,NaN,NaN,NaN,NaN,1.75,5.45,17.65,1.75,4.412500,0.643598

In [83]:
def fetch_features(compounds, collection, features='all', column_name=None, statistical_functions='all'):
    if isinstance(compounds, str):
        # return get_features(compounds,collection,features)
        if features !='all' and isinstance(features, str):
            values= [statistical_features(compounds,collection,features,statistical_functions)[1]]
            names = statistical_features(compounds,collection,features,statistical_functions)[0]
            return pd.DataFrame(values,columns=names,index=[compounds])
        else :
            n_features=len(statistical_features(compounds,collection,features,statistical_functions))
            n_elements=len(statistical_features(compounds,collection,features,statistical_functions)[0][0])
            tmp_array=np.array(statistical_features(compounds,collection,features,statistical_functions))
            names=list(tmp_array[:,0].reshape(1,n_features*n_elements)[0])
            values=tmp_array[:,1].reshape(1,n_features*n_elements)
            return pd.DataFrame(values,columns=names,index=[compounds])
    if isinstance(compounds, list):
        tmp_df=pd.DataFrame(compounds,columns=["formula"])
        # return tmp_df
        return statistical_features_df(tmp_df,"formula",collection,features,statistical_functions)
    if isinstance(compounds, pd.DataFrame):
        tmp_dataframe_name=compounds.copy(deep=True)
        if (column_name==None):
            raise ValueError("The input is `pd.DataFrame` and `column_name` argument is not given. Please inter materials column name.")
        else :
            return statistical_features_df(tmp_dataframe_name,column_name,collection,features,statistical_functions=statistical_functions)

In [84]:
lst=['min','max']

In [85]:
fetch_features('Rb3Sb2Br9' , mendeleev,  'atomic_number',statistical_functions='min')

           atomic_number_min
Rb3Sb2Br9                 16

In [86]:
fetch_features('Rb3Sb2Br9' , mendeleev,  'atomic_number',statistical_functions=lst)

           atomic_number_min  atomic_number_max
Rb3Sb2Br9                 16                 51

In [87]:
fetch_features('Rb3Sb2Br9' , mendeleev,  'atomic_number')

,atomic_number_min,atomic_number_max,atomic_number_sum,atomic_number_diff,atomic_number_mean,atomic_number_std
Rb3Sb2Br9,16,51,123,16,41.0,7.118052

In [88]:
lst_f=['atomic_number','atomic_weight']

In [89]:
fetch_features('Rb3Sb2Br9' , mendeleev,  features=lst_f,statistical_functions='min')

          atomic_number_min  atomic_weight_min
Rb3Sb2Br9                16  41.85600000000001

In [90]:
fetch_features('Rb3Sb2Br9' , mendeleev,  features=lst_f,statistical_functions=lst)

,atomic_number_min,atomic_number_max,atomic_weight_min,atomic_weight_max
Rb3Sb2Br9,16,51,41.85600000000001,121.76

In [91]:
fetch_features('Rb3Sb2Br9' , mendeleev,  features=lst_f)

,atomic_number_min,atomic_number_max,atomic_number_sum,atomic_number_diff,atomic_number_mean,atomic_number_std,atomic_weight_min,atomic_weight_max,atomic_weight_sum,atomic_weight_diff,atomic_weight_mean,atomic_weight_std
Rb3Sb2Br9,16,51,123,16,41.0,7.118052168020874,41.85600000000001,121.76,287.1318,41.85600000000001,95.7106,18.559227675741255

In [92]:
fetch_features('Rb3Sb2Br9' , mendel,  statistical_functions='min')

,neutrons_min,mass_number_min,hardness_min,softness_min,Zeff_slater_min
Rb3Sb2Br9,26,42,2.3795069,0.15257393154512844,5.399999999999999

In [93]:
mendel

    chemical_symbol  neutrons  mass_number   hardness  softness  Zeff_slater
0                 H         0            1   6.422120  0.077856         1.00
1                He         2            4  22.143694  0.022580         1.70
2                Li         4            7   2.386833  0.209483         1.30
3                Be         5            9   5.861350  0.085305         1.95
4                 B         6           11   4.009148  0.124715         2.60
..              ...       ...          ...        ...       ...          ...
113              Fl       173          287        NaN       NaN         5.65
114              Mc       173          288        NaN       NaN         6.30
115              Lv       175          291        NaN       NaN         6.95
116              Ts       176          293        NaN       NaN         7.60
117              Og       176          294        NaN       NaN         8.25

[118 rows x 6 columns]

In [94]:
fetch_features('Rb3Sb2Br9' , mendel,  statistical_functions=lst)

,neutrons_min,neutrons_max,mass_number_min,mass_number_max,hardness_min,hardness_max,softness_min,softness_max,Zeff_slater_min,Zeff_slater_max
Rb3Sb2Br9,26,70,42,121,2.3795069,4.2251109,0.15257393154512844,0.2709140205591232,5.399999999999999,7.600000000000001

In [95]:
fetch_features('Rb3Sb2Br9' , mendel)

,neutrons_min,neutrons_max,neutrons_sum,neutrons_diff,neutrons_mean,neutrons_std,mass_number_min,mass_number_max,mass_number_sum,mass_number_diff,...,softness_sum,softness_diff,softness_mean,softness_std,Zeff_slater_min,Zeff_slater_max,Zeff_slater_sum,Zeff_slater_diff,Zeff_slater_mean,Zeff_slater_std
Rb3Sb2Br9,26,70,162,26,54.0,11.430952132988164,42,121,285,42,...,0.521487455411318,0.15257393154512844,0.17382915180377267,0.06888328027530126,5.399999999999999,7.600000000000001,16.10000000000001,5.399999999999999,5.36666666666667,2.3012074125457604

In [96]:
# fetch_features(['RbBr'] , mendel,  features='all')
fetch_features(['RbBr','Al2O3'],mendel,features='hardness',statistical_functions='min')

  formula  hardness_min
0    RbBr      2.379507
1   Al2O3      3.302001

In [97]:
fetch_features(['RbBr','Al2O3'],mendel,features='hardness',statistical_functions=lst)

  formula  hardness_min  hardness_max
0    RbBr      2.379507      4.225111
1   Al2O3      3.302001      6.078470

In [98]:
fetch_features(['RbBr','Al2O3'],mendel,features='hardness')

,formula,hardness_min,hardness_max,hardness_sum,hardness_diff,hardness_mean,hardness_std
0,RbBr,2.379507,4.225111,6.070715,2.379507,3.035357,1.189753
1,Al2O3,3.302001,6.078470,8.854939,3.302001,4.427470,1.651001

In [99]:
fetch_features(['RbBr','Al2O3'],mendeleev,features=lst_f,statistical_functions='min')

  formula  atomic_number_min  atomic_weight_min
0    RbBr                  2           5.563800
1   Al2O3                  5          10.982538

In [100]:
fetch_features(['RbBr','Al2O3'],mendeleev,features=lst_f,statistical_functions=lst)

,formula,atomic_number_min,atomic_number_max,atomic_weight_min,atomic_weight_max
0,RbBr,2,37,5.563800,85.467800
1,Al2O3,5,13,10.982538,26.981538

In [101]:
fetch_features(['RbBr','Al2O3'],mendeleev,features=lst_f)

,formula,atomic_number_min,atomic_number_max,atomic_number_sum,atomic_number_diff,atomic_number_mean,atomic_number_std,atomic_weight_min,atomic_weight_max,atomic_weight_sum,atomic_weight_diff,atomic_weight_mean,atomic_weight_std
0,RbBr,2,37,72,2,36.0,1.0,5.563800,85.467800,165.371800,5.563800,82.685900,2.781900
1,Al2O3,5,13,21,5,10.5,2.5,10.982538,26.981538,42.980539,10.982538,21.490269,5.491269

In [102]:
fetch_features(['RbBr','Al2O3'],mendel)

,formula,neutrons_min,neutrons_max,neutrons_sum,neutrons_diff,neutrons_mean,neutrons_std,mass_number_min,mass_number_max,mass_number_sum,...,softness_sum,softness_diff,softness_mean,softness_std,Zeff_slater_min,Zeff_slater_max,Zeff_slater_sum,Zeff_slater_diff,Zeff_slater_mean,Zeff_slater_std
0,RbBr,4,48,92,4,46.0,2.0,6,85,164,...,0.389254,0.152574,0.194627,0.076287,5.40,7.60,9.80,5.40,4.900,2.700
1,Al2O3,6,14,22,6,11.0,3.0,11,27,43,...,0.262342,0.097827,0.131171,0.048914,1.05,4.55,8.05,1.05,4.025,0.525

In [103]:
fetch_features(primary_data,mendel,column_name='formula',features='hardness',statistical_functions='min')

              formula  space group  bandgap  hardness_min
mp-28222    Rb3Sb2Br9          164   1.9796      2.379507
mp-17756    RbAg2SbS4          154   0.6178      2.295849
mp-30373         RbAu          221   0.3699      1.612857
mp-22867         RbBr          225   4.1920      2.379507
mp-23295         RbCl          225   4.8388      2.831848
...               ...          ...      ...           ...
mp-10519      Cu2SnS3            9   0.0183      1.025528
mp-11658     Cu2SnSe3            9   0.0000      0.749936
mp-1861         Cu2Te          191   0.0000      0.273702
mp-10824   ZnCu2GeSe4          121   0.0000           NaN
mp-977414   ZnCu2SiS4           31   1.2823           NaN

[471 rows x 4 columns]

In [104]:
fetch_features(primary_data,mendel,column_name='formula',features='hardness',statistical_functions=lst)

              formula  space group  bandgap  hardness_min  hardness_max
mp-28222    Rb3Sb2Br9          164   1.9796      2.379507      4.225111
mp-17756    RbAg2SbS4          154   0.6178      2.295849      4.141453
mp-30373         RbAu          221   0.3699      1.612857      3.458461
mp-22867         RbBr          225   4.1920      2.379507      4.225111
mp-23295         RbCl          225   4.8388      2.831848      4.677452
...               ...          ...      ...           ...           ...
mp-10519      Cu2SnS3            9   0.0183      1.025528      4.141453
mp-11658     Cu2SnSe3            9   0.0000      0.749936      3.865861
mp-1861         Cu2Te          191   0.0000      0.273702      3.519392
mp-10824   ZnCu2GeSe4          121   0.0000           NaN           NaN
mp-977414   ZnCu2SiS4           31   1.2823           NaN           NaN

[471 rows x 5 columns]

In [105]:
fetch_features(primary_data,mendel,column_name='formula',features='hardness')

,formula,space group,bandgap,hardness_min,hardness_max,hardness_sum,hardness_diff,hardness_mean,hardness_std
mp-28222,Rb3Sb2Br9,164,1.9796,2.379507,4.225111,9.851909,2.379507,3.283970,1.033098
mp-17756,RbAg2SbS4,154,0.6178,2.295849,4.141453,12.905368,2.295849,3.226342,0.874598
mp-30373,RbAu,221,0.3699,1.612857,3.458461,5.304066,1.612857,2.652033,0.806429
mp-22867,RbBr,225,4.1920,2.379507,4.225111,6.070715,2.379507,3.035357,1.189753
mp-23295,RbCl,225,4.8388,2.831848,4.677452,6.523056,2.831848,3.261528,1.415924
...,...,...,...,...,...,...,...,...,...
mp-10519,Cu2SnS3,9,0.0183,1.025528,4.141453,10.503068,1.025528,3.501023,0.455941
mp-11658,Cu2SnSe3,9,0.0000,0.749936,3.865861,10.227476,0.749936,3.409159,0.327254
mp-1861,Cu2Te,191,0.0000,0.273702,3.519392,6.765082,0.273702,3.382541,0.136851
mp-10824,ZnCu2GeSe4,121,0.0000,NaN,NaN,NaN,NaN,NaN,NaN
mp-977414,ZnCu2SiS4,31,1.2823,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
fetch_features(primary_data,mendeleev,column_name='formula',features=lst_f,statistical_functions='min')

,formula,space group,bandgap,atomic_number_min,atomic_weight_min
mp-28222,Rb3Sb2Br9,164,1.9796,16,41.856000
mp-17756,RbAg2SbS4,154,0.6178,35,89.700000
mp-30373,RbAu,221,0.3699,42,111.498769
mp-22867,RbBr,225,4.1920,2,5.563800
mp-23295,RbCl,225,4.8388,20,50.017800
...,...,...,...,...,...
mp-10519,Cu2SnS3,9,0.0183,34,86.650000
mp-11658,Cu2SnSe3,9,0.0000,21,55.164000
mp-1861,Cu2Te,191,0.0000,23,64.054000
mp-10824,ZnCu2GeSe4,121,0.0000,5,15.425000
mp-977414,ZnCu2SiS4,31,1.2823,16,37.295000

In [107]:
fetch_features(primary_data,mendeleev,column_name='formula',features=lst_f,statistical_functions=lst)

,formula,space group,bandgap,atomic_number_min,atomic_number_max,atomic_weight_min,atomic_weight_max
mp-28222,Rb3Sb2Br9,164,1.9796,16,51,41.856000,121.760000
mp-17756,RbAg2SbS4,154,0.6178,35,51,89.700000,121.760000
mp-30373,RbAu,221,0.3699,42,79,111.498769,196.966569
mp-22867,RbBr,225,4.1920,2,37,5.563800,85.467800
mp-23295,RbCl,225,4.8388,20,37,50.017800,85.467800
...,...,...,...,...,...,...,...
mp-10519,Cu2SnS3,9,0.0183,34,50,86.650000,118.710000
mp-11658,Cu2SnSe3,9,0.0000,21,50,55.164000,118.710000
mp-1861,Cu2Te,191,0.0000,23,52,64.054000,127.600000
mp-10824,ZnCu2GeSe4,121,0.0000,5,34,15.425000,78.971000
mp-977414,ZnCu2SiS4,31,1.2823,16,30,37.295000,65.380000

In [108]:
fetch_features(primary_data,mendeleev,column_name='formula',features=lst_f)

,formula,space group,bandgap,atomic_number_min,atomic_number_max,atomic_number_sum,atomic_number_diff,atomic_number_mean,atomic_number_std,atomic_weight_min,atomic_weight_max,atomic_weight_sum,atomic_weight_diff,atomic_weight_mean,atomic_weight_std
mp-28222,Rb3Sb2Br9,164,1.9796,16,51,123,16,41.000000,7.118052,41.856000,121.760000,287.131800,41.856000,95.710600,18.559228
mp-17756,RbAg2SbS4,154,0.6178,35,51,151,35,37.750000,13.553136,89.700000,121.760000,347.156000,89.700000,86.789000,34.147886
mp-30373,RbAu,221,0.3699,42,79,116,42,58.000000,21.000000,111.498769,196.966569,282.434369,111.498769,141.217185,55.749384
mp-22867,RbBr,225,4.1920,2,37,72,2,36.000000,1.000000,5.563800,85.467800,165.371800,5.563800,82.685900,2.781900
mp-23295,RbCl,225,4.8388,20,37,54,20,27.000000,10.000000,50.017800,85.467800,120.917800,50.017800,60.458900,25.008900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
mp-10519,Cu2SnS3,9,0.0183,34,50,95,34,31.666667,14.007934,86.650000,118.710000,214.316000,86.650000,71.438667,35.812254
mp-11658,Cu2SnSe3,9,0.0000,21,50,113,21,37.666667,8.956686,55.164000,118.710000,261.227000,55.164000,87.075667,23.238344
mp-1861,Cu2Te,191,0.0000,23,52,81,23,40.500000,11.500000,64.054000,127.600000,191.146000,64.054000,95.573000,32.027000
mp-10824,ZnCu2GeSe4,121,0.0000,5,34,125,5,31.250000,1.920286,15.425000,78.971000,280.527000,15.425000,70.131750,6.130351
mp-977414,ZnCu2SiS4,31,1.2823,16,30,89,16,22.250000,7.292976,37.295000,65.380000,189.071000,37.295000,47.267750,17.264766

In [109]:
fetch_features(primary_data,mendel,column_name='formula',features='all',statistical_functions='min')

,formula,space group,bandgap,neutrons_min,mass_number_min,hardness_min,softness_min,Zeff_slater_min
mp-28222,Rb3Sb2Br9,164,1.9796,26,42,2.379507,0.152574,5.40
mp-17756,RbAg2SbS4,154,0.6178,54,89,2.295849,0.150183,4.10
mp-30373,RbAu,221,0.3699,70,112,1.612857,0.126341,1.50
mp-22867,RbBr,225,4.1920,4,6,2.379507,0.152574,5.40
mp-23295,RbCl,225,4.8388,30,50,2.831848,0.164018,3.90
...,...,...,...,...,...,...,...,...
mp-10519,Cu2SnS3,9,0.0183,54,88,1.025528,0.039735,1.95
mp-11658,Cu2SnSe3,9,0.0000,36,57,0.749936,0.031129,3.25
mp-1861,Cu2Te,191,0.0000,44,67,0.273702,0.011980,3.25
mp-10824,ZnCu2GeSe4,121,0.0000,12,17,NaN,NaN,3.25
mp-977414,ZnCu2SiS4,31,1.2823,20,36,NaN,NaN,1.75

In [110]:
fetch_features(primary_data,mendel,column_name='formula',features='all',statistical_functions=lst)

,formula,space group,bandgap,neutrons_min,neutrons_max,mass_number_min,mass_number_max,hardness_min,hardness_max,softness_min,softness_max,Zeff_slater_min,Zeff_slater_max
mp-28222,Rb3Sb2Br9,164,1.9796,26,70,42,121,2.379507,4.225111,0.152574,0.270914,5.40,7.60
mp-17756,RbAg2SbS4,154,0.6178,54,70,89,121,2.295849,4.141453,0.150183,0.270914,4.10,6.30
mp-30373,RbAu,221,0.3699,70,118,112,197,1.612857,3.458461,0.126341,0.270914,1.50,3.70
mp-22867,RbBr,225,4.1920,4,48,6,85,2.379507,4.225111,0.152574,0.270914,5.40,7.60
mp-23295,RbCl,225,4.8388,30,48,50,85,2.831848,4.677452,0.164018,0.270914,3.90,6.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
mp-10519,Cu2SnS3,9,0.0183,54,70,88,120,1.025528,4.141453,0.039735,0.160466,1.95,5.65
mp-11658,Cu2SnSe3,9,0.0000,36,70,57,120,0.749936,3.865861,0.031129,0.160466,3.25,6.95
mp-1861,Cu2Te,191,0.0000,44,78,67,130,0.273702,3.519392,0.011980,0.154050,3.25,6.95
mp-10824,ZnCu2GeSe4,121,0.0000,12,46,17,80,NaN,NaN,NaN,NaN,3.25,6.95
mp-977414,ZnCu2SiS4,31,1.2823,20,34,36,64,NaN,NaN,NaN,NaN,1.75,5.45

In [111]:
fetch_features(primary_data,mendele,column_name='formula')

,formula,space group,bandgap,neutrons_min,neutrons_max,neutrons_sum,neutrons_diff,neutrons_mean,neutrons_std,mass_number_min,...,softness_sum,softness_diff,softness_mean,softness_std,Zeff_slater_min,Zeff_slater_max,Zeff_slater_sum,Zeff_slater_diff,Zeff_slater_mean,Zeff_slater_std
mp-28222,Rb3Sb2Br9,164,1.9796,26,70,162,26,54.0,11.430952,42,...,0.521487,0.152574,0.173829,0.068883,5.40,7.60,16.10,5.40,5.366667,2.301207
mp-17756,RbAg2SbS4,154,0.6178,54,70,194,54,48.5,20.316250,89,...,0.683260,0.150183,0.170815,0.059472,4.10,6.30,17.65,4.10,4.412500,1.584446
mp-30373,RbAu,221,0.3699,70,118,166,70,83.0,35.000000,112,...,0.415487,0.126341,0.207743,0.063171,1.50,3.70,5.90,1.50,2.950000,0.750000
mp-22867,RbBr,225,4.1920,4,48,92,4,46.0,2.000000,6,...,0.389254,0.152574,0.194627,0.076287,5.40,7.60,9.80,5.40,4.900000,2.700000
mp-23295,RbCl,225,4.8388,30,48,66,30,33.0,15.000000,50,...,0.377810,0.164018,0.188905,0.082009,3.90,6.10,8.30,3.90,4.150000,1.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
mp-10519,Cu2SnS3,9,0.0183,54,70,120,54,40.0,22.449944,88,...,0.435247,0.039735,0.145082,0.017417,1.95,5.65,14.80,1.95,4.933333,0.875912
mp-11658,Cu2SnSe3,9,0.0000,36,70,150,36,50.0,14.966630,57,...,0.443854,0.031129,0.147951,0.013420,3.25,6.95,16.30,3.25,5.433333,1.335623
mp-1861,Cu2Te,191,0.0000,44,78,112,44,56.0,22.000000,67,...,0.296120,0.011980,0.148060,0.005990,3.25,6.95,10.65,3.25,5.325000,1.625000
mp-10824,ZnCu2GeSe4,121,0.0000,12,46,156,12,39.0,5.196152,17,...,NaN,NaN,NaN,NaN,3.25,6.95,20.65,3.25,5.162500,1.248186
mp-977414,ZnCu2SiS4,31,1.2823,20,34,98,20,24.5,9.526279,36,...,NaN,NaN,NaN,NaN,1.75,5.45,17.65,1.75,4.412500,0.643598

In [112]:
fetch_features(primary_data,mendeleev,column_name='formula')

,formula,space group,bandgap,neutrons_min,neutrons_max,neutrons_sum,neutrons_diff,neutrons_mean,neutrons_std,mass_number_min,...,electronegativity_pauling_sum,electronegativity_pauling_diff,electronegativity_pauling_mean,electronegativity_pauling_std,electronegativity_sanderson_min,electronegativity_sanderson_max,electronegativity_sanderson_sum,electronegativity_sanderson_diff,electronegativity_sanderson_mean,electronegativity_sanderson_std
mp-28222,Rb3Sb2Br9,164,1.9796,26,70,162,26,54.0,11.430952,42,...,5.83,2.14,1.943333,0.876901,0.872612,1.049026,2.001712,0.872612,0.667237,0.364490
mp-17756,RbAg2SbS4,154,0.6178,54,70,194,54,48.5,20.316250,89,...,7.38,1.76,1.845000,0.640332,0.767382,0.943795,2.536206,0.767382,0.634052,0.285321
mp-30373,RbAu,221,0.3699,70,118,166,70,83.0,35.000000,112,...,3.22,1.58,1.610000,0.790000,1.250287,1.426701,1.603114,1.250287,0.801557,0.625144
mp-22867,RbBr,225,4.1920,4,48,92,4,46.0,2.000000,6,...,3.78,2.14,1.890000,1.070000,0.872612,1.049026,1.225439,0.872612,0.612720,0.436306
mp-23295,RbCl,225,4.8388,30,48,66,30,33.0,15.000000,50,...,3.98,2.34,1.990000,1.170000,0.635964,0.812377,0.988791,0.635964,0.494395,0.317982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
mp-10519,Cu2SnS3,9,0.0183,54,70,120,54,40.0,22.449944,88,...,6.44,0.68,2.146667,0.307390,0.277829,0.917554,2.319559,0.277829,0.773186,0.113685
mp-11658,Cu2SnSe3,9,0.0000,36,70,150,36,50.0,14.966630,57,...,6.41,0.65,2.136667,0.293295,0.203632,0.965912,2.645746,0.203632,0.881915,0.086868
mp-1861,Cu2Te,191,0.0000,44,78,112,44,56.0,22.000000,67,...,4.00,0.20,2.000000,0.100000,0.055304,0.917554,1.779805,0.055304,0.889902,0.027652
mp-10824,ZnCu2GeSe4,121,0.0000,12,46,156,12,39.0,5.196152,17,...,8.11,0.90,2.027500,0.328662,0.165765,0.965912,3.493701,0.165765,0.873425,0.070503
mp-977414,ZnCu2SiS4,31,1.2823,20,34,98,20,24.5,9.526279,36,...,8.03,0.93,2.007500,0.345932,0.570738,0.917554,2.714183,0.570738,0.678546,0.215627